# This project's RuboCop configuration
# Inherits from Cookpad's Ruby Style Guide and applies project-specific overrides

inherit_from: .rubocop.cookpad-styleguide.yml

# Additional plugins
plugins:
  - rubocop-rspec

# Project-specific overrides

Metrics/ClassLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 10

RSpec/ContextWording:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
